server :
  port : 1234
spring :
  zipkin:
    enabled: true
    service.name: service-b-logging
    sender.type: web
    base-url: http://localhost:9411
    sleuth:
      enabled: true
      sampler:
        probability: 1.0
  application :
    name : service-b-logging